/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-24 10:07:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hal.hrms.model.User;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.hal.hrms.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User currentUser = (User) session.getAttribute("currentUser");
    if (currentUser == null) {
        response.sendRedirect("login");
        return;
    }
    Integer totalEmployees = (Integer) request.getAttribute("totalEmployees");
    Integer adminCount = (Integer) request.getAttribute("adminCount");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Dashboard - HAL HR Seniority System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --hal-navy: #0A2540;\r\n");
      out.write("            --hal-blue: #004b87;\r\n");
      out.write("            --hal-accent: #007bc4;\r\n");
      out.write("            --text-dark: #2d3748;\r\n");
      out.write("            --text-light: #718096;\r\n");
      out.write("            --bg-light: #f7fafc;\r\n");
      out.write("            --bg-card: #ffffff;\r\n");
      out.write("            --border-color: #cbd5e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* App Layout Grid */\r\n");
      out.write("        .app-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar Navigation */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 260px;\r\n");
      out.write("            background-color: var(--hal-navy);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding: 1.5rem 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-brand {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding-bottom: 2rem;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-menu {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-item a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: rgba(255,255,255,0.8);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-item a:hover,\r\n");
      out.write("        .sidebar-item.active a {\r\n");
      out.write("            background-color: var(--hal-blue);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            padding-left: 1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Section */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            border-bottom: 1px solid var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar-title {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-profile {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-badge {\r\n");
      out.write("            background-color: #e2e8f0;\r\n");
      out.write("            padding: 0.25rem 0.75rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-logout {\r\n");
      out.write("            color: #e53e3e;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-container {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Card Component */\r\n");
      out.write("        .card {\r\n");
      out.write("            background-color: var(--bg-card);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("            margin-bottom: 1.25rem;\r\n");
      out.write("            border-bottom: 2px solid var(--bg-light);\r\n");
      out.write("            padding-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Stats Blocks */\r\n");
      out.write("        .stats-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card {\r\n");
      out.write("            background-color: var(--bg-card);\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            transition: transform 0.3s cubic-bezier(0.25, 0.8, 0.25, 1), box-shadow 0.3s ease, border-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card:hover {\r\n");
      out.write("            transform: translateY(-4px);\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0, 75, 135, 0.12);\r\n");
      out.write("            border-color: var(--hal-blue);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-label {\r\n");
      out.write("            font-size: 0.875rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* --- HAL JET ANIMATIONS --- */\r\n");
      out.write("        @keyframes jetFloat {\r\n");
      out.write("            0% { transform: translateY(0) rotate(-35deg) scale(1); }\r\n");
      out.write("            50% { transform: translateY(-8px) rotate(-33deg) scale(1.03); }\r\n");
      out.write("            100% { transform: translateY(0) rotate(-35deg) scale(1); }\r\n");
      out.write("        }\r\n");
      out.write("        .jet-animated {\r\n");
      out.write("            animation: jetFloat 6s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes jetGlide {\r\n");
      out.write("            0% { transform: translate(-100px, 10px) rotate(45deg) scale(0.6); opacity: 0; }\r\n");
      out.write("            30% { opacity: 0.25; }\r\n");
      out.write("            100% { transform: translate(120px, -10px) rotate(45deg) scale(0.8); opacity: 0; }\r\n");
      out.write("        }\r\n");
      out.write("        .jet-glide {\r\n");
      out.write("            animation: jetGlide 3.5s cubic-bezier(0.25, 0.8, 0.25, 1) forwards;\r\n");
      out.write("            animation-delay: 0.5s;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-value {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons styling */\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 0.625rem 1.25rem;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: 1px solid transparent;\r\n");
      out.write("            transition: background-color 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: var(--hal-blue);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background-color: #e2e8f0;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            border-color: var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background-color: #cbd5e0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"app-container\" style=\"position: relative; padding-top: 4px;\">\r\n");
      out.write("        <!-- Tricolor Top Accent -->\r\n");
      out.write("        <div style=\"height: 4px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%); z-index: 100;\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar Navigation -->\r\n");
      out.write("        <div class=\"sidebar\" style=\"position: relative; overflow: hidden; padding-top: 2rem;\">\r\n");
      out.write("            <!-- Jet watermark inside sidebar -->\r\n");
      out.write("            <svg class=\"jet-animated\" style=\"position: absolute; bottom: -20px; right: -20px; width: 120px; height: 120px; opacity: 0.05; transform-origin: center; color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\r\n");
      out.write("                <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-brand\" style=\"display: flex; align-items: center; justify-content: center; padding: 0.5rem; background: #ffffff; border-radius: 6px; margin: 0 0.5rem 1.5rem 0.5rem; z-index: 10; box-shadow: 0 2px 8px rgba(0,0,0,0.2);\">\r\n");
      out.write("                <img src=\"images/hal-logo.png\" alt=\"HAL Logo\" style=\"max-width: 100%; height: auto; max-height: 38px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"sidebar-menu\">\r\n");
      out.write("                <li class=\"sidebar-item active\"><a href=\"dashboard\">Dashboard</a></li>\r\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"seniority\">Seniority Engine</a></li>\r\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"employees?action=list\">Employee Roster</a></li>\r\n");
      out.write("                ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                    <li class=\"sidebar-item\"><a href=\"employees?action=new\">Add Employee</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li class=\"sidebar-item\" style=\"margin-top: auto;\"><a href=\"logout\" class=\"btn-logout\" style=\"color: #ff8888;\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content Area -->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <!-- Header Top Bar -->\r\n");
      out.write("            <div class=\"top-bar\">\r\n");
      out.write("                <div class=\"top-bar-title\">HR Seniority Management System - Overhaul Division</div>\r\n");
      out.write("                <div class=\"user-profile\">\r\n");
      out.write("                    <span class=\"user-badge\">");
      out.print( currentUser.getUserRole() );
      out.write("</span>\r\n");
      out.write("                    <span>Welcome, <strong>");
      out.print( currentUser.getEmployeeName() );
      out.write("</strong></span>\r\n");
      out.write("                    <a href=\"logout\" class=\"btn-logout\">Logout</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Page Container -->\r\n");
      out.write("            <div class=\"page-container\">\r\n");
      out.write("                <div style=\"margin-bottom: 2rem; position: relative; overflow: hidden;\">\r\n");
      out.write("                    <h2 style=\"color: var(--hal-navy); font-weight: 700;\">HR Management Portal</h2>\r\n");
      out.write("                    <p style=\"color: var(--text-light);\">Hindustan Aeronautics Limited - Overhaul Division, Bangalore</p>\r\n");
      out.write("                    <!-- Jet silhouette that glides across title when page loads -->\r\n");
      out.write("                    <div style=\"position: absolute; right: 0; top: 0; width: 100px; height: 40px; overflow: hidden; pointer-events: none;\">\r\n");
      out.write("                        <svg class=\"jet-glide\" viewBox=\"0 0 100 100\" fill=\"currentColor\" style=\"width: 24px; height: 24px; color: var(--hal-blue); opacity: 0.15; transform: rotate(90deg);\">\r\n");
      out.write("                            <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Statistics Grid -->\r\n");
      out.write("                <div class=\"stats-grid\">\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <span class=\"stat-label\">Total Employee Files</span>\r\n");
      out.write("                        <span class=\"stat-value\">");
      out.print( totalEmployees != null ? totalEmployees.toString() : "0" );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <span class=\"stat-label\">Authorized HR Operators</span>\r\n");
      out.write("                        <span class=\"stat-value\">");
      out.print( adminCount != null ? adminCount.toString() : "0" );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stat-card\">\r\n");
      out.write("                        <span class=\"stat-label\">Active Grades</span>\r\n");
      out.write("                        <span class=\"stat-value\">10</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Quick Action Panels -->\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3 class=\"card-title\">Quick HR Operations</h3>\r\n");
      out.write("                    <div style=\"display: flex; gap: 1rem; flex-wrap: wrap;\">\r\n");
      out.write("                        <a href=\"seniority\" class=\"btn btn-primary\">Open Seniority Engine</a>\r\n");
      out.write("                        <a href=\"employees?action=list\" class=\"btn btn-secondary\">Search & View Roster</a>\r\n");
      out.write("                        ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                            <a href=\"employees?action=new\" class=\"btn btn-secondary\">Register New Employee</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- PSU Compliance Notice -->\r\n");
      out.write("                <div class=\"card\" style=\"border-left: 4px solid var(--hal-accent);\">\r\n");
      out.write("                    <h4 style=\"color: var(--hal-navy); margin-bottom: 0.5rem; font-weight: 600;\">System Notification & Guidelines</h4>\r\n");
      out.write("                    <p style=\"font-size: 0.9rem; color: var(--text-dark);\">\r\n");
      out.write("                        Seniority calculation is generated dynamically based on official grade-promotion timelines. \r\n");
      out.write("                        To preserve audit trails, all operations performed (updates, modifications, and deletions) \r\n");
      out.write("                        are automatically captured in the database audit log.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
