/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-24 10:45:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hal.hrms.model.Employee;
import com.hal.hrms.model.User;
import com.hal.hrms.model.Promotion;

public final class employee_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hal.hrms.model.Promotion");
    _jspx_imports_classes.add("com.hal.hrms.model.Employee");
    _jspx_imports_classes.add("com.hal.hrms.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    User currentUser = (User) session.getAttribute("currentUser");
    if (currentUser == null) {
        response.sendRedirect("login");
        return;
    }
    List employeeList = (List) request.getAttribute("employeeList");
    String searchQuery = (String) request.getAttribute("searchQuery");
    if (searchQuery == null) {
        searchQuery = "";
    }
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MMM-yyyy");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Employee Roster - HAL HR Seniority System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --hal-navy: #0A2540;\r\n");
      out.write("            --hal-blue: #004b87;\r\n");
      out.write("            --hal-accent: #007bc4;\r\n");
      out.write("            --text-dark: #2d3748;\r\n");
      out.write("            --text-light: #718096;\r\n");
      out.write("            --bg-light: #f7fafc;\r\n");
      out.write("            --bg-card: #ffffff;\r\n");
      out.write("            --border-color: #cbd5e0;\r\n");
      out.write("            --danger-red: #e53e3e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .app-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar Styling */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 260px;\r\n");
      out.write("            background-color: var(--hal-navy);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding: 1.5rem 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-brand {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding-bottom: 2rem;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-menu {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-item a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: rgba(255,255,255,0.8);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar-item a:hover,\r\n");
      out.write("        .sidebar-item.active a {\r\n");
      out.write("            background-color: var(--hal-blue);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            padding-left: 1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content Container */\r\n");
      out.write("        .main-content {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            padding: 0 2rem;\r\n");
      out.write("            border-bottom: 1px solid var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .top-bar-title {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-profile {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-badge {\r\n");
      out.write("            background-color: #e2e8f0;\r\n");
      out.write("            padding: 0.25rem 0.75rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-logout {\r\n");
      out.write("            color: #e53e3e;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-container {\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Card Component */\r\n");
      out.write("        .card {\r\n");
      out.write("            background-color: var(--bg-card);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("            margin-bottom: 1.25rem;\r\n");
      out.write("            border-bottom: 2px solid var(--bg-light);\r\n");
      out.write("            padding-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Tables */\r\n");
      out.write("        .table-responsive {\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .data-table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-top: 1rem;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .data-table th {\r\n");
      out.write("            background-color: var(--hal-navy);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border: 1px solid var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .data-table td {\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            border-bottom: 1px solid var(--border-color);\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .data-table tbody tr:nth-child(even) {\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .data-table tbody tr:hover {\r\n");
      out.write("            background-color: #ebf8ff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Forms inputs */\r\n");
      out.write("        .form-control {\r\n");
      out.write("            padding: 0.625rem;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: var(--hal-blue);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons styling */\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 0.625rem 1.25rem;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: 1px solid transparent;\r\n");
      out.write("            transition: background-color 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: var(--hal-blue);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: var(--hal-navy);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background-color: #e2e8f0;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            border-color: var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background-color: #cbd5e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .actions-bar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media print {\r\n");
      out.write("            .sidebar, .top-bar, .actions-bar, .btn, .no-print, form {\r\n");
      out.write("                display: none !important;\r\n");
      out.write("            }\r\n");
      out.write("            .main-content {\r\n");
      out.write("                padding: 0 !important;\r\n");
      out.write("            }\r\n");
      out.write("            .page-container {\r\n");
      out.write("                padding: 0 !important;\r\n");
      out.write("                max-width: 100% !important;\r\n");
      out.write("            }\r\n");
      out.write("            .card {\r\n");
      out.write("                border: none !important;\r\n");
      out.write("                box-shadow: none !important;\r\n");
      out.write("                padding: 0 !important;\r\n");
      out.write("            }\r\n");
      out.write("            .data-table th {\r\n");
      out.write("                background-color: #f2f2f2 !important;\r\n");
      out.write("                color: #000000 !important;\r\n");
      out.write("                border: 1px solid #000000 !important;\r\n");
      out.write("                white-space: normal !important;\r\n");
      out.write("            }\r\n");
      out.write("            .data-table td {\r\n");
      out.write("                border: 1px solid #000000 !important;\r\n");
      out.write("                white-space: normal !important;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Backdrop */\r\n");
      out.write("        .modal-overlay {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("            background-color: rgba(10, 37, 64, 0.4);\r\n");
      out.write("            backdrop-filter: blur(8px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(8px);\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Container */\r\n");
      out.write("        .modal-container {\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 650px;\r\n");
      out.write("            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            animation: modalSlideUp 0.3s ease-out;\r\n");
      out.write("            max-height: 85vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes modalSlideUp {\r\n");
      out.write("            from {\r\n");
      out.write("                transform: translateY(30px);\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Header */\r\n");
      out.write("        .modal-header {\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            border-bottom: 1px solid var(--border-color);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("            border-top-left-radius: 12px;\r\n");
      out.write("            border-top-right-radius: 12px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-header-title {\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .modal-header-subtitle {\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            margin-top: 0.25rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-modal-close {\r\n");
      out.write("            background: none;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            font-size: 1.75rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("            padding: 0.25rem;\r\n");
      out.write("            transition: color 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-modal-close:hover {\r\n");
      out.write("            color: var(--danger-red);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Body */\r\n");
      out.write("        .modal-body {\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Timeline Tree/List */\r\n");
      out.write("        .timeline-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-left: 2rem;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            border-left: 2px solid var(--border-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item:last-child {\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-badge {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: calc(-2rem - 7px);\r\n");
      out.write("            top: 6px;\r\n");
      out.write("            width: 12px;\r\n");
      out.write("            height: 12px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            background-color: var(--border-color);\r\n");
      out.write("            border: 2px solid #ffffff;\r\n");
      out.write("            box-shadow: 0 0 0 2px var(--border-color);\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item.primary-assignment .timeline-badge {\r\n");
      out.write("            background-color: var(--hal-accent);\r\n");
      out.write("            box-shadow: 0 0 0 2px var(--hal-accent);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-card {\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid var(--border-color);\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-item.primary-assignment .timeline-card {\r\n");
      out.write("            border-left: 4px solid var(--hal-accent);\r\n");
      out.write("            background-color: #f0f7ff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            margin-bottom: 0.75rem;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-designation {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: var(--hal-navy);\r\n");
      out.write("            font-size: 1.05rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Assignment Type Tags */\r\n");
      out.write("        .assignment-type-tag {\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            padding: 0.2rem 0.6rem;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-trainee {\r\n");
      out.write("            background-color: #edf2f7;\r\n");
      out.write("            color: #4a5568;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-absorption {\r\n");
      out.write("            background-color: #ebf8ff;\r\n");
      out.write("            color: #2b6cb0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-cps {\r\n");
      out.write("            background-color: #e6fffa;\r\n");
      out.write("            color: #234e52;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-dpc {\r\n");
      out.write("            background-color: #faf5ff;\r\n");
      out.write("            color: #553c9a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-transfer {\r\n");
      out.write("            background-color: #fffaf0;\r\n");
      out.write("            color: #dd6b20;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-job-rotation {\r\n");
      out.write("            background-color: #f0fff4;\r\n");
      out.write("            color: #22543d;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-revised-designation {\r\n");
      out.write("            background-color: #e2e8f0;\r\n");
      out.write("            color: #4a5568;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .type-additional-responsibilities {\r\n");
      out.write("            background-color: #fff5f5;\r\n");
      out.write("            color: #9b2c2c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .timeline-details {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            font-size: 0.85rem;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .detail-item strong {\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .no-history {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: var(--text-light);\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("         * Exports HTML Table data directly into a CSV Spreadsheet.\r\n");
      out.write("         * Works natively in client web browser without server load.\r\n");
      out.write("         */\r\n");
      out.write("        function exportTableToCSV(tableId, filename) {\r\n");
      out.write("            var csv = [];\r\n");
      out.write("            var table = document.getElementById(tableId);\r\n");
      out.write("            if (!table) return;\r\n");
      out.write("\r\n");
      out.write("            var rows = table.querySelectorAll(\"tr\");\r\n");
      out.write("            \r\n");
      out.write("            for (var i = 0; i < rows.length; i++) {\r\n");
      out.write("                var row = [];\r\n");
      out.write("                var cols = rows[i].querySelectorAll(\"td, th\");\r\n");
      out.write("                \r\n");
      out.write("                // Skip the Actions column header and cell data if this is admin view\r\n");
      out.write("                var limit = cols.length;\r\n");
      out.write("                var isAdmin = \"");
      out.print( currentUser.getUserRole() );
      out.write("\" === \"ADMIN\";\r\n");
      out.write("                if (isAdmin && i > 0) {\r\n");
      out.write("                    limit = cols.length - 1; // skip last td (actions)\r\n");
      out.write("                } else if (isAdmin && i == 0) {\r\n");
      out.write("                    limit = cols.length - 1; // skip last th (actions)\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                for (var j = 0; j < limit; j++) {\r\n");
      out.write("                    var cellText = cols[j].innerText.trim();\r\n");
      out.write("                    cellText = cellText.replace(/\"/g, '\"\"'); // Escape double quotes\r\n");
      out.write("                    row.push('\"' + cellText + '\"');\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                csv.push(row.join(\",\"));\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var csvFile = new Blob([csv.join(\"\\n\")], { type: \"text/csv;charset=utf-8;\" });\r\n");
      out.write("            var downloadLink = document.createElement(\"a\");\r\n");
      out.write("            \r\n");
      out.write("            downloadLink.download = filename;\r\n");
      out.write("            downloadLink.href = window.URL.createObjectURL(csvFile);\r\n");
      out.write("            downloadLink.style.display = \"none\";\r\n");
      out.write("            document.body.appendChild(downloadLink);\r\n");
      out.write("            downloadLink.click();\r\n");
      out.write("            document.body.removeChild(downloadLink);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"app-container\" style=\"position: relative; padding-top: 4px;\">\r\n");
      out.write("        <!-- Tricolor Top Accent -->\r\n");
      out.write("        <div style=\"height: 4px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%); z-index: 100;\"></div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar Navigation -->\r\n");
      out.write("        <div class=\"sidebar\" style=\"position: relative; overflow: hidden; padding-top: 2rem;\">\r\n");
      out.write("            <!-- Jet watermark inside sidebar -->\r\n");
      out.write("            <svg style=\"position: absolute; bottom: -20px; right: -20px; width: 120px; height: 120px; opacity: 0.05; transform: rotate(-35deg); color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\r\n");
      out.write("                <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sidebar-brand\" style=\"display: flex; align-items: center; justify-content: center; padding: 0.5rem; background: #ffffff; border-radius: 6px; margin: 0 0.5rem 1.5rem 0.5rem; z-index: 10; box-shadow: 0 2px 8px rgba(0,0,0,0.2);\">\r\n");
      out.write("                <img src=\"images/hal-logo.png\" alt=\"HAL Logo\" style=\"max-width: 100%; height: auto; max-height: 38px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"sidebar-menu\">\r\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"dashboard\">Dashboard</a></li>\r\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"seniority\">Seniority Engine</a></li>\r\n");
      out.write("                <li class=\"sidebar-item active\"><a href=\"employees?action=list\">Employee Roster</a></li>\r\n");
      out.write("                ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                    <li class=\"sidebar-item\"><a href=\"employees?action=new\">Add Employee</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li class=\"sidebar-item\" style=\"margin-top: auto;\"><a href=\"logout\" class=\"btn-logout\" style=\"color: #ff8888;\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content Area -->\r\n");
      out.write("        <div class=\"main-content\">\r\n");
      out.write("            <div class=\"top-bar\">\r\n");
      out.write("                <div class=\"top-bar-title\">Employee Records Directory - Overhaul Division</div>\r\n");
      out.write("                <div class=\"user-profile\">\r\n");
      out.write("                    <span class=\"user-badge\">");
      out.print( currentUser.getUserRole() );
      out.write("</span>\r\n");
      out.write("                    <span>Welcome, <strong>");
      out.print( currentUser.getEmployeeName() );
      out.write("</strong></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Page Content -->\r\n");
      out.write("            <div class=\"page-container\">\r\n");
      out.write("                <div class=\"actions-bar\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h2 style=\"color: var(--hal-navy); font-weight: 700;\">Active Employees Roster</h2>\r\n");
      out.write("                        <p style=\"color: var(--text-light); font-size: 0.9rem;\">Maintain active profiles and trace administrative parameters.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                            <a href=\"employees?action=new\" class=\"btn btn-primary\">+ Add New Employee</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Search Card -->\r\n");
      out.write("                <div class=\"card\" style=\"padding: 1rem;\">\r\n");
      out.write("                    <form action=\"employees\" method=\"get\" style=\"display: flex; gap: 1rem; align-items: center;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"list\">\r\n");
      out.write("                        <input type=\"text\" name=\"query\" class=\"form-control\" placeholder=\"Search by ID, Name, Department, or Designation...\" value=\"");
      out.print( searchQuery );
      out.write("\" style=\"flex: 1;\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Search</button>\r\n");
      out.write("                        ");
 if (!"".equals(searchQuery)) { 
      out.write("\r\n");
      out.write("                            <a href=\"employees?action=list\" class=\"btn btn-secondary\">Clear</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Roster Grid -->\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;\">\r\n");
      out.write("                        <h3 class=\"card-title\" style=\"margin-bottom: 0; border: none;\">Employee Directory Listings</h3>\r\n");
      out.write("                        <button onclick=\"exportTableToCSV('rosterTable', 'hal_employee_roster.csv')\" class=\"btn btn-secondary\">Export to CSV</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        ");

                            boolean[] activeGrades = new boolean[11]; // index 1 to 10
                            int activeGradesCount = 0;
                            if (employeeList != null && !employeeList.isEmpty()) {
                                for (int i = 0; i < employeeList.size(); i++) {
                                    Employee emp = (Employee) employeeList.get(i);
                                    for (int g = 1; g <= 10; g++) {
                                        if (emp.getPromotionDateForGrade("Grade " + g) != null) {
                                            if (!activeGrades[g]) {
                                                activeGrades[g] = true;
                                                activeGradesCount++;
                                            }
                                        }
                                    }
                                }
                            }
                            if (activeGradesCount == 0) {
                                if (employeeList != null && !employeeList.isEmpty()) {
                                    Employee emp = (Employee) employeeList.get(0);
                                    String gName = emp.getGrade();
                                    if (gName != null && gName.startsWith("Grade ")) {
                                        try {
                                            int g = Integer.parseInt(gName.substring(6).trim());
                                            activeGrades[g] = true;
                                            activeGradesCount = 1;
                                        } catch (Exception e) {}
                                    }
                                }
                            }
                            int totalColsCount = ("ADMIN".equals(currentUser.getUserRole()) ? 9 : 8) + activeGradesCount;
                        
      out.write("\r\n");
      out.write("                        <table class=\"data-table\" id=\"rosterTable\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Employee ID</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Full Name</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Grade</th>\r\n");
      out.write("                                    ");
 if (activeGradesCount > 0) { 
      out.write("\r\n");
      out.write("                                        <th colspan=\"");
      out.print( activeGradesCount );
      out.write("\" style=\"text-align: center; border-bottom: 1px solid rgba(255,255,255,0.2);\">Promotion Dates per Grade (Position)</th>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Joining</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Birth</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Retirement Date</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Department</th>\r\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Designation</th>\r\n");
      out.write("                                    ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                                        <th rowspan=\"2\" class=\"no-print\" style=\"width: 130px; text-align: center; vertical-align: middle;\">Actions</th>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    ");
 for (int g = 10; g >= 1; g--) {
                                        if (activeGrades[g]) {
                                            String dName = Employee.getDesignationForGrade("Grade " + g);
                                            String shortD = dName.indexOf("(") > -1 ? dName.substring(dName.indexOf("(")+1, dName.indexOf(")")) : dName;
                                    
      out.write("\r\n");
      out.write("                                        <th style=\"font-size: 0.8rem; padding: 0.5rem; text-align: center; min-width: 90px;\">\r\n");
      out.write("                                            Gr ");
      out.print( g );
      out.write("<br><span style=\"font-size:0.7rem; font-weight:normal; opacity:0.85;\">");
      out.print( shortD );
      out.write("</span>\r\n");
      out.write("                                        </th>\r\n");
      out.write("                                    ");
 
                                        }
                                    } 
      out.write("\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                ");

                                    if (employeeList != null && !employeeList.isEmpty()) {
                                        for (int i = 0; i < employeeList.size(); i++) {
                                            Employee emp = (Employee) employeeList.get(i);
                                
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><strong>");
      out.print( emp.getEmployeeId() );
      out.write("</strong></td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <a href=\"javascript:void(0)\" onclick=\"showTimelineModal('");
      out.print( emp.getEmployeeId() );
      out.write("')\" style=\"color: var(--hal-blue); text-decoration: underline; font-weight: 600;\">");
      out.print( emp.getEmployeeName() );
      out.write("</a>\r\n");
      out.write("                                            <div id=\"history-data-");
      out.print( emp.getEmployeeId() );
      out.write("\" style=\"display: none;\">\r\n");
      out.write("                                                [\r\n");
      out.write("                                                ");

                                                    List history = emp.getHistoryList();
                                                    if (history != null) {
                                                        for (int j = 0; j < history.size(); j++) {
                                                            Promotion promo = (Promotion) history.get(j);
                                                            String validFromStr = promo.getValidFrom() != null ? sdf.format(promo.getValidFrom()) : "N/A";
                                                            String validToStr = promo.getValidTo() != null ? sdf.format(promo.getValidTo()) : "Present";
                                                            String promoDateStr = promo.getPromotionDate() != null ? sdf.format(promo.getPromotionDate()) : "N/A";
                                                            String des = promo.getDesignation() != null ? promo.getDesignation() : "";
                                                            des = des.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String gr = promo.getGrade() != null ? promo.getGrade() : "";
                                                            gr = gr.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String type = promo.getAssignmentType() != null ? promo.getAssignmentType() : "";
                                                            type = type.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String ord = promo.getOrderNumber() != null ? promo.getOrderNumber() : "N/A";
                                                            ord = ord.replace("\\", "\\\\").replace("\"", "\\\"");
                                                
      out.write("\r\n");
      out.write("                                                    {\r\n");
      out.write("                                                        \"grade\": \"");
      out.print( gr );
      out.write("\",\r\n");
      out.write("                                                        \"promotionDate\": \"");
      out.print( promoDateStr );
      out.write("\",\r\n");
      out.write("                                                        \"designation\": \"");
      out.print( des );
      out.write("\",\r\n");
      out.write("                                                        \"validFrom\": \"");
      out.print( validFromStr );
      out.write("\",\r\n");
      out.write("                                                        \"validTo\": \"");
      out.print( validToStr );
      out.write("\",\r\n");
      out.write("                                                        \"isPrimary\": ");
      out.print( promo.getIsPrimary() );
      out.write(",\r\n");
      out.write("                                                        \"assignmentType\": \"");
      out.print( type );
      out.write("\",\r\n");
      out.write("                                                        \"orderNumber\": \"");
      out.print( ord );
      out.write("\"\r\n");
      out.write("                                                    }");
      out.print( (j < history.size() - 1) ? "," : "" );
      out.write("\r\n");
      out.write("                                                ");

                                                        }
                                                    }
                                                
      out.write("\r\n");
      out.write("                                                ]\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td>");
      out.print( emp.getGrade() );
      out.write("</td>\r\n");
      out.write("                                        \r\n");
      out.write("                                        ");
 for (int g = 10; g >= 1; g--) {
                                            if (activeGrades[g]) {
                                                java.util.Date pDate = emp.getPromotionDateForGrade("Grade " + g);
                                        
      out.write("\r\n");
      out.write("                                            <td style=\"text-align: center; font-size: 0.85rem;\">\r\n");
      out.write("                                                ");
      out.print( pDate != null ? sdf.format(pDate) : "-" );
      out.write("\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        ");
 
                                            }
                                        } 
      out.write("\r\n");
      out.write("                                        \r\n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfJoining()) );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfBirth()) );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( emp.getDateOfRetirement() != null ? sdf.format(emp.getDateOfRetirement()) : "N/A" );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( emp.getDepartment() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( emp.getDesignation() );
      out.write("</td>\r\n");
      out.write("                                        ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\r\n");
      out.write("                                            <td class=\"no-print\" style=\"text-align: center;\">\r\n");
      out.write("                                                <a href=\"employees?action=edit&id=");
      out.print( emp.getEmployeeId() );
      out.write("\" style=\"color: var(--hal-blue); text-decoration: none; font-weight: bold; margin-right: 0.75rem;\">Edit</a>\r\n");
      out.write("                                                <a href=\"employees?action=delete&id=");
      out.print( emp.getEmployeeId() );
      out.write("\" onclick=\"return confirm('Are you sure you want to delete this employee?');\" style=\"color: var(--danger-red); text-decoration: none; font-weight: bold;\">Delete</a>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");

                                        }
                                    } else {
                                
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td colspan=\"");
      out.print( totalColsCount );
      out.write("\" style=\"text-align: center; color: var(--text-light); padding: 2rem;\">\r\n");
      out.write("                                            No employee records found.\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Timeline Modal -->\r\n");
      out.write("    <div id=\"timelineModal\" class=\"modal-overlay\">\r\n");
      out.write("        <div class=\"modal-container\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h3 class=\"modal-header-title\" id=\"modalEmployeeName\">Employee Name</h3>\r\n");
      out.write("                    <div class=\"modal-header-subtitle\">Employee ID: <span id=\"modalEmployeeId\">N/A</span></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn-modal-close\" onclick=\"closeTimelineModal()\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"timeline-wrapper\" id=\"timelineContent\">\r\n");
      out.write("                    <!-- Dynamic Timeline Content will be inserted here -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function showTimelineModal(empId) {\r\n");
      out.write("            var dataElement = document.getElementById(\"history-data-\" + empId);\r\n");
      out.write("            var history = [];\r\n");
      out.write("            if (dataElement) {\r\n");
      out.write("                try {\r\n");
      out.write("                    history = JSON.parse(dataElement.textContent || dataElement.innerText);\r\n");
      out.write("                } catch(e) {\r\n");
      out.write("                    console.error(\"Error parsing history JSON for employee \" + empId, e);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            var empName = \"\";\r\n");
      out.write("            \r\n");
      out.write("            // Find employee name\r\n");
      out.write("            var rows = document.querySelectorAll(\"#rosterTable tbody tr\");\r\n");
      out.write("            for (var i = 0; i < rows.length; i++) {\r\n");
      out.write("                var cellId = rows[i].cells[0].innerText.trim();\r\n");
      out.write("                if (cellId === empId) {\r\n");
      out.write("                    // Link is inside the second cell\r\n");
      out.write("                    empName = rows[i].cells[1].innerText.trim();\r\n");
      out.write("                    break;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById(\"modalEmployeeId\").innerText = empId;\r\n");
      out.write("            document.getElementById(\"modalEmployeeName\").innerText = empName;\r\n");
      out.write("            \r\n");
      out.write("            var timelineContainer = document.getElementById(\"timelineContent\");\r\n");
      out.write("            timelineContainer.innerHTML = \"\";\r\n");
      out.write("            \r\n");
      out.write("            if (!history || history.length === 0) {\r\n");
      out.write("                timelineContainer.innerHTML = \"<div class='no-history'>No promotion or assignment history recorded for this employee.</div>\";\r\n");
      out.write("            } else {\r\n");
      out.write("                // Sort history by validFrom to make sure it's chronological\r\n");
      out.write("                var months = { \"Jan\":0, \"Feb\":1, \"Mar\":2, \"Apr\":3, \"May\":4, \"Jun\":5, \"Jul\":6, \"Aug\":7, \"Sep\":8, \"Oct\":9, \"Nov\":10, \"Dec\":11 };\r\n");
      out.write("                function parseCustomDate(dateStr) {\r\n");
      out.write("                    if (!dateStr || dateStr === \"N/A\" || dateStr === \"Present\") return new Date();\r\n");
      out.write("                    var parts = dateStr.split(\"-\");\r\n");
      out.write("                    if (parts.length < 3) return new Date();\r\n");
      out.write("                    var day = parseInt(parts[0], 10);\r\n");
      out.write("                    var month = months[parts[1]];\r\n");
      out.write("                    var year = parseInt(parts[2], 10);\r\n");
      out.write("                    return new Date(year, month, day);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                // Clone and sort\r\n");
      out.write("                var sortedHistory = [];\r\n");
      out.write("                for (var k = 0; k < history.length; k++) {\r\n");
      out.write("                    sortedHistory.push(history[k]);\r\n");
      out.write("                }\r\n");
      out.write("                sortedHistory.sort(function(a, b) {\r\n");
      out.write("                    return parseCustomDate(a.validFrom) - parseCustomDate(b.validFrom);\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                var html = \"\";\r\n");
      out.write("                for (var i = 0; i < sortedHistory.length; i++) {\r\n");
      out.write("                    var item = sortedHistory[i];\r\n");
      out.write("                    var badgeClass = item.isPrimary ? \"badge-primary\" : \"badge-secondary\";\r\n");
      out.write("                    var typeClass = \"type-\" + item.assignmentType.toLowerCase().replace(/[^a-z0-9]/g, \"-\");\r\n");
      out.write("                    \r\n");
      out.write("                    html += \"<div class='timeline-item \" + (item.isPrimary ? \"primary-assignment\" : \"\") + \"'>\";\r\n");
      out.write("                    html += \"  <div class='timeline-badge \" + badgeClass + \"'></div>\";\r\n");
      out.write("                    html += \"  <div class='timeline-card'>\";\r\n");
      out.write("                    html += \"    <div class='timeline-header'>\";\r\n");
      out.write("                    html += \"      <span class='timeline-designation'>Pos Code: \" + item.designation + \"</span>\";\r\n");
      out.write("                    html += \"      <span class='assignment-type-tag \" + typeClass + \"'>\" + item.assignmentType + \"</span>\";\r\n");
      out.write("                    html += \"    </div>\";\r\n");
      out.write("                    html += \"    <div class='timeline-details'>\";\r\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Grade:</strong> \" + item.grade + \"</div>\";\r\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Promotion Date:</strong> \" + item.promotionDate + \"</div>\";\r\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Duration:</strong> \" + item.validFrom + \" to \" + item.validTo + \"</div>\";\r\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Order Number:</strong> \" + item.orderNumber + \"</div>\";\r\n");
      out.write("                    html += \"    </div>\";\r\n");
      out.write("                    html += \"  </div>\";\r\n");
      out.write("                    html += \"</div>\";\r\n");
      out.write("                }\r\n");
      out.write("                timelineContainer.innerHTML = html;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById(\"timelineModal\").style.display = \"flex\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function closeTimelineModal() {\r\n");
      out.write("            document.getElementById(\"timelineModal\").style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Close modal on click outside content\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            var modal = document.getElementById(\"timelineModal\");\r\n");
      out.write("            if (event.target == modal) {\r\n");
      out.write("                modal.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
