/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-22 15:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hal.hrms.model.Employee;
import com.hal.hrms.model.User;

public final class seniority_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hal.hrms.model.Employee");
    _jspx_imports_classes.add("com.hal.hrms.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User currentUser = (User) session.getAttribute("currentUser");
    if (currentUser == null) {
        response.sendRedirect("login");
        return;
    }
    List seniorityList = (List) request.getAttribute("seniorityList");
    String selectedGrade = (String) request.getAttribute("selectedGrade");
    if (selectedGrade == null) {
        selectedGrade = "ALL";
    }
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MMM-yyyy");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Seniority Engine - HAL HR Seniority System</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --hal-navy: #0A2540;\n");
      out.write("            --hal-blue: #004b87;\n");
      out.write("            --hal-accent: #007bc4;\n");
      out.write("            --text-dark: #2d3748;\n");
      out.write("            --text-light: #718096;\n");
      out.write("            --bg-light: #f7fafc;\n");
      out.write("            --bg-card: #ffffff;\n");
      out.write("            --border-color: #cbd5e0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("            line-height: 1.5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .app-container {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar Navigation */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 260px;\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            color: #ffffff;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            padding: 1.5rem 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-brand {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            padding-bottom: 2rem;\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a {\n");
      out.write("            display: block;\n");
      out.write("            color: rgba(255,255,255,0.8);\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a:hover,\n");
      out.write("        .sidebar-item.active a {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("            padding-left: 1.25rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Workspace */\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            height: 70px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            padding: 0 2rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar-title {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-profile {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-badge {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            padding: 0.25rem 0.75rem;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-logout {\n");
      out.write("            color: #e53e3e;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-container {\n");
      out.write("            padding: 2rem;\n");
      out.write("            max-width: 1200px;\n");
      out.write("            width: 100%;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Cards styling */\n");
      out.write("        .card {\n");
      out.write("            background-color: var(--bg-card);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-title {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            margin-bottom: 1.25rem;\n");
      out.write("            border-bottom: 2px solid var(--bg-light);\n");
      out.write("            padding-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Data Tables */\n");
      out.write("        .table-responsive {\n");
      out.write("            overflow-x: auto;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table th {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            color: #ffffff;\n");
      out.write("            text-align: left;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border: 1px solid var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table td {\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table tbody tr:nth-child(even) {\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table tbody tr:hover {\n");
      out.write("            background-color: #ebf8ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Forms Dropdown */\n");
      out.write("        .form-control {\n");
      out.write("            padding: 0.625rem;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            outline: none;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: var(--hal-blue);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Action Buttons */\n");
      out.write("        .btn {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 0.625rem 1.25rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border: 1px solid transparent;\n");
      out.write("            transition: background-color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            border-color: var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background-color: #cbd5e0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .actions-bar {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            gap: 1rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* CSS Print Template for PDF Generation */\n");
      out.write("        @media print {\n");
      out.write("            .sidebar, .top-bar, .actions-bar, .btn, .no-print {\n");
      out.write("                display: none !important;\n");
      out.write("            }\n");
      out.write("            .main-content {\n");
      out.write("                padding: 0 !important;\n");
      out.write("            }\n");
      out.write("            .page-container {\n");
      out.write("                padding: 0 !important;\n");
      out.write("                max-width: 100% !important;\n");
      out.write("            }\n");
      out.write("            .card {\n");
      out.write("                border: none !important;\n");
      out.write("                box-shadow: none !important;\n");
      out.write("                padding: 0 !important;\n");
      out.write("            }\n");
      out.write("            .data-table th {\n");
      out.write("                background-color: #f2f2f2 !important;\n");
      out.write("                color: #000000 !important;\n");
      out.write("                border: 1px solid #000000 !important;\n");
      out.write("                white-space: normal !important;\n");
      out.write("            }\n");
      out.write("            .data-table td {\n");
      out.write("                border: 1px solid #000000 !important;\n");
      out.write("                white-space: normal !important;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function handleGradeChange() {\n");
      out.write("            var grade = document.getElementById(\"gradeFilter\").value;\n");
      out.write("            window.location.href = \"seniority?gradeFilter=\" + encodeURIComponent(grade);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"app-container\" style=\"position: relative; padding-top: 4px;\">\n");
      out.write("        <!-- Tricolor Top Accent -->\n");
      out.write("        <div style=\"height: 4px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%); z-index: 100;\"></div>\n");
      out.write("\n");
      out.write("        <!-- Sidebar Navigation -->\n");
      out.write("        <div class=\"sidebar\" style=\"position: relative; overflow: hidden; padding-top: 2rem;\">\n");
      out.write("            <!-- Jet watermark inside sidebar -->\n");
      out.write("            <svg style=\"position: absolute; bottom: -20px; right: -20px; width: 120px; height: 120px; opacity: 0.05; transform: rotate(-35deg); color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\n");
      out.write("                <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\n");
      out.write("            </svg>\n");
      out.write("\n");
      out.write("            <div class=\"sidebar-brand\" style=\"display: flex; align-items: center; justify-content: center; padding: 0.5rem; background: #ffffff; border-radius: 6px; margin: 0 0.5rem 1.5rem 0.5rem; z-index: 10; box-shadow: 0 2px 8px rgba(0,0,0,0.2);\">\n");
      out.write("                <img src=\"images/hal-logo.png\" alt=\"HAL Logo\" style=\"max-width: 100%; height: auto; max-height: 38px;\">\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"dashboard\">Dashboard</a></li>\n");
      out.write("                <li class=\"sidebar-item active\"><a href=\"seniority\">Seniority Engine</a></li>\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"employees?action=list\">Employee Roster</a></li>\n");
      out.write("                ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\n");
      out.write("                    <li class=\"sidebar-item\"><a href=\"employees?action=new\">Add Employee</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <li class=\"sidebar-item\" style=\"margin-top: auto;\"><a href=\"logout\" class=\"btn-logout\" style=\"color: #ff8888;\">Logout</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Content Area -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <div class=\"top-bar-title\">Seniority Calculations Engine - Overhaul Division</div>\n");
      out.write("                <div class=\"user-profile\">\n");
      out.write("                    <span class=\"user-badge\">");
      out.print( currentUser.getUserRole() );
      out.write("</span>\n");
      out.write("                    <span>Welcome, <strong>");
      out.print( currentUser.getEmployeeName() );
      out.write("</strong></span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Page Container -->\n");
      out.write("            <div class=\"page-container\">\n");
      out.write("                <div class=\"actions-bar\">\n");
      out.write("                    <div>\n");
      out.write("                        <h2 style=\"color: var(--hal-navy); font-weight: 700;\">Dynamic Seniority Rankings</h2>\n");
      out.write("                        <p style=\"color: var(--text-light); font-size: 0.9rem;\">Rankings are computed dynamically using the 7-level fallback seniority algorithm.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"no-print\" style=\"display: flex; gap: 0.5rem;\">\n");
      out.write("                        <button onclick=\"window.print()\" class=\"btn btn-secondary\">Print Report / PDF</button>\n");
      out.write("                        <!-- Server-Side Export (Fully Java 1.4 Native) -->\n");
      out.write("                        <a href=\"seniority?gradeFilter=");
      out.print( selectedGrade );
      out.write("&export=csv\" class=\"btn btn-primary\">Download CSV</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Grade Selection Filter -->\n");
      out.write("                <div class=\"card no-print\">\n");
      out.write("                    <div style=\"display: flex; align-items: center; gap: 1rem; flex-wrap: wrap;\">\n");
      out.write("                        <label for=\"gradeFilter\" class=\"form-label\" style=\"margin-bottom: 0; white-space: nowrap;\">Filter Seniority List by Grade:</label>\n");
      out.write("                        <select id=\"gradeFilter\" name=\"gradeFilter\" class=\"form-control\" style=\"max-width: 250px;\" onchange=\"handleGradeChange()\">\n");
      out.write("                            <option value=\"ALL\" ");
      out.print( "ALL".equals(selectedGrade) ? "selected" : "" );
      out.write(">All Grades (Global Ranks)</option>\n");
      out.write("                            ");
 for (int g = 1; g <= 10; g++) { 
                                String currentG = "Grade " + g;
                                boolean selected = currentG.equals(selectedGrade);
                            
      out.write("\n");
      out.write("                                <option value=\"");
      out.print( currentG );
      out.write('"');
      out.write(' ');
      out.print( selected ? "selected" : "" );
      out.write('>');
      out.print( currentG );
      out.write(' ');
      out.write('(');
      out.print( Employee.getDesignationForGrade(currentG) );
      out.write(")</option>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                        <span style=\"font-size: 0.85rem; color: var(--text-light);\">\n");
      out.write("                            Selecting a single grade shows the internal seniority ranks of employees in that grade.\n");
      out.write("                        </span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Seniority Table -->\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h3 class=\"card-title\">\n");
      out.write("                        ");
      out.print( "ALL".equals(selectedGrade) ? "Organization-Wide Seniority Listings" : selectedGrade + " Seniority Rankings" );
      out.write("\n");
      out.write("                    </h3>\n");
      out.write("\n");
      out.write("                    <div class=\"table-responsive\">\n");
      out.write("                        ");

                            boolean[] activeGrades = new boolean[11]; // index 1 to 10
                            int activeGradesCount = 0;
                            if (seniorityList != null && !seniorityList.isEmpty()) {
                                for (int i = 0; i < seniorityList.size(); i++) {
                                    Employee emp = (Employee) seniorityList.get(i);
                                    for (int g = 1; g <= 10; g++) {
                                        if (emp.getPromotionDateForGrade("Grade " + g) != null) {
                                            if (!activeGrades[g]) {
                                                activeGrades[g] = true;
                                                activeGradesCount++;
                                            }
                                        }
                                    }
                                }
                            }
                            if (activeGradesCount == 0) {
                                if (selectedGrade != null && selectedGrade.startsWith("Grade ")) {
                                    try {
                                        int g = Integer.parseInt(selectedGrade.substring(6).trim());
                                        activeGrades[g] = true;
                                        activeGradesCount = 1;
                                    } catch (Exception e) {}
                                } else if (seniorityList != null && !seniorityList.isEmpty()) {
                                    Employee emp = (Employee) seniorityList.get(0);
                                    String gName = emp.getGrade();
                                    if (gName != null && gName.startsWith("Grade ")) {
                                        try {
                                            int g = Integer.parseInt(gName.substring(6).trim());
                                            activeGrades[g] = true;
                                            activeGradesCount = 1;
                                        } catch (Exception e) {}
                                    }
                                }
                            }
                            
                            int totalColsCount = 4 + activeGradesCount + 5;
                        
      out.write("\n");
      out.write("                        <table class=\"data-table\" id=\"seniorityTable\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th rowspan=\"2\" style=\"width: 80px; text-align: center; vertical-align: middle;\">Rank</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Employee ID</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Employee Name</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Grade</th>\n");
      out.write("                                    ");
 if (activeGradesCount > 0) { 
      out.write("\n");
      out.write("                                        <th colspan=\"");
      out.print( activeGradesCount );
      out.write("\" style=\"text-align: center; border-bottom: 1px solid rgba(255,255,255,0.2);\">Promotion Dates per Grade (Position)</th>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Joining</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Birth</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Retirement Date</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Department</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Designation</th>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    ");
 for (int g = 10; g >= 1; g--) { 
                                        if (activeGrades[g]) {
                                            String dName = Employee.getDesignationForGrade("Grade " + g);
                                            String shortD = dName.indexOf("(") > -1 ? dName.substring(dName.indexOf("(")+1, dName.indexOf(")")) : dName;
                                    
      out.write("\n");
      out.write("                                        <th style=\"font-size: 0.8rem; padding: 0.5rem; text-align: center; min-width: 90px;\">\n");
      out.write("                                            Gr ");
      out.print( g );
      out.write("<br><span style=\"font-size:0.7rem; font-weight:normal; opacity:0.85;\">");
      out.print( shortD );
      out.write("</span>\n");
      out.write("                                        </th>\n");
      out.write("                                    ");
 
                                        }
                                    } 
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");

                                    if (seniorityList != null && !seniorityList.isEmpty()) {
                                        for (int i = 0; i < seniorityList.size(); i++) {
                                            Employee emp = (Employee) seniorityList.get(i);
                                
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td style=\"text-align: center;\"><strong>");
      out.print( emp.getRank() );
      out.write("</strong></td>\n");
      out.write("                                        <td><strong>");
      out.print( emp.getEmployeeId() );
      out.write("</strong></td>\n");
      out.write("                                        <td>");
      out.print( emp.getEmployeeName() );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getGrade() );
      out.write("</td>\n");
      out.write("                                        \n");
      out.write("                                        ");
 for (int g = 10; g >= 1; g--) { 
                                            if (activeGrades[g]) {
                                                java.util.Date pDate = emp.getPromotionDateForGrade("Grade " + g);
                                        
      out.write("\n");
      out.write("                                            <td style=\"text-align: center; font-size: 0.85rem;\">\n");
      out.write("                                                ");
      out.print( pDate != null ? sdf.format(pDate) : "-" );
      out.write("\n");
      out.write("                                            </td>\n");
      out.write("                                        ");
 
                                            }
                                        } 
      out.write("\n");
      out.write("                                        \n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfJoining()) );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfBirth()) );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDateOfRetirement() != null ? sdf.format(emp.getDateOfRetirement()) : "N/A" );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDepartment() );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDesignation() );
      out.write("</td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");

                                        }
                                    } else {
                                
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td colspan=\"");
      out.print( totalColsCount );
      out.write("\" style=\"text-align: center; color: var(--text-light); padding: 2rem;\">\n");
      out.write("                                            No employee records found in this grade category.\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");

                                    }
                                
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
