/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-18 15:05:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hal.hrms.model.Employee;
import com.hal.hrms.model.User;

public final class employee_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.hal.hrms.model.Employee");
    _jspx_imports_classes.add("com.hal.hrms.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    User currentUser = (User) session.getAttribute("currentUser");
    if (currentUser == null || !"ADMIN".equals(currentUser.getUserRole())) {
        response.sendRedirect("login");
        return;
    }
    
    Boolean isEditObj = (Boolean) request.getAttribute("isEdit");
    boolean isEdit = isEditObj != null && isEditObj.booleanValue();
    Employee emp = (Employee) request.getAttribute("employee");
    if (emp == null) {
        emp = new Employee();
    }
    
    java.text.SimpleDateFormat sdfInput = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String promoDateStr = emp.getPromotionDate() != null ? sdfInput.format(emp.getPromotionDate()) : "";
    String dojDateStr = emp.getDateOfJoining() != null ? sdfInput.format(emp.getDateOfJoining()) : "";
    String dobDateStr = emp.getDateOfBirth() != null ? sdfInput.format(emp.getDateOfBirth()) : "";
    
    String error = (String) request.getAttribute("error");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>");
      out.print( isEdit ? "Edit Profile" : "Register Employee" );
      out.write(" - HAL HR Seniority System</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --hal-navy: #0A2540;\n");
      out.write("            --hal-blue: #004b87;\n");
      out.write("            --text-dark: #2d3748;\n");
      out.write("            --text-light: #718096;\n");
      out.write("            --bg-light: #f7fafc;\n");
      out.write("            --bg-card: #ffffff;\n");
      out.write("            --border-color: #cbd5e0;\n");
      out.write("            --danger-red: #e53e3e;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("            line-height: 1.5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .app-container {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar Styling */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 260px;\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            color: #ffffff;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            padding: 1.5rem 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-brand {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            padding-bottom: 2rem;\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a {\n");
      out.write("            display: block;\n");
      out.write("            color: rgba(255,255,255,0.8);\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a:hover,\n");
      out.write("        .sidebar-item.active a {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("            padding-left: 1.25rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Area */\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            height: 70px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            padding: 0 2rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar-title {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-profile {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-badge {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            padding: 0.25rem 0.75rem;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-logout {\n");
      out.write("            color: #e53e3e;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-container {\n");
      out.write("            padding: 2rem;\n");
      out.write("            max-width: 1200px;\n");
      out.write("            width: 100%;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Card components */\n");
      out.write("        .card {\n");
      out.write("            background-color: var(--bg-card);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-title {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            margin-bottom: 1.25rem;\n");
      out.write("            border-bottom: 2px solid var(--bg-light);\n");
      out.write("            padding-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Forms Layout & Controls */\n");
      out.write("        .form-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n");
      out.write("            gap: 1.5rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 0.375rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            padding: 0.625rem;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            width: 100%;\n");
      out.write("            outline: none;\n");
      out.write("            background-color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: var(--hal-blue);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Buttons */\n");
      out.write("        .btn {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 0.625rem 1.25rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border: 1px solid transparent;\n");
      out.write("            transition: background-color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            border-color: var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background-color: #cbd5e0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-message {\n");
      out.write("            background-color: #fff5f5;\n");
      out.write("            border-left: 4px solid var(--danger-red);\n");
      out.write("            color: var(--danger-red);\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .actions-bar {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            gap: 1rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        /**\n");
      out.write("         * Validates Employee Creation/Edition Form\n");
      out.write("         */\n");
      out.write("        function validateEmployeeForm() {\n");
      out.write("            var empId = document.getElementById(\"employeeId\").value.trim();\n");
      out.write("            var empName = document.getElementById(\"employeeName\").value.trim();\n");
      out.write("            var dobStr = document.getElementById(\"dateOfBirth\").value;\n");
      out.write("            var dojStr = document.getElementById(\"dateOfJoining\").value;\n");
      out.write("            var promoStr = document.getElementById(\"promotionDate\").value;\n");
      out.write("\n");
      out.write("            if (empId === \"\" || empName === \"\") {\n");
      out.write("                alert(\"Employee ID and Name cannot be blank.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if (empId.length < 3) {\n");
      out.write("                alert(\"Please enter a valid Employee ID.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            if (!dobStr || !dojStr || !promoStr) {\n");
      out.write("                alert(\"Please fill in all date fields (Date of Birth, Date of Joining, Promotion Date).\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var dob = new Date(dobStr);\n");
      out.write("            var doj = new Date(dojStr);\n");
      out.write("            var promo = new Date(promoStr);\n");
      out.write("\n");
      out.write("            // Rule: DOJ must be after DOB (at least 18 years old)\n");
      out.write("            var ageAtJoining = doj.getFullYear() - dob.getFullYear();\n");
      out.write("            if (ageAtJoining < 18) {\n");
      out.write("                alert(\"Validation Error: Date of Joining must represent an age of at least 18 years from Date of Birth.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // Rule: Promotion date must be on or after DOJ\n");
      out.write("            if (promo < doj) {\n");
      out.write("                alert(\"Validation Error: Current Grade Promotion Date cannot be earlier than Date of Joining.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"app-container\" style=\"position: relative; padding-top: 4px;\">\n");
      out.write("        <!-- Tricolor Top Accent -->\n");
      out.write("        <div style=\"height: 4px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%); z-index: 100;\"></div>\n");
      out.write("\n");
      out.write("        <!-- Sidebar Navigation -->\n");
      out.write("        <div class=\"sidebar\" style=\"position: relative; overflow: hidden; padding-top: 2rem;\">\n");
      out.write("            <!-- Jet watermark inside sidebar -->\n");
      out.write("            <svg style=\"position: absolute; bottom: -20px; right: -20px; width: 120px; height: 120px; opacity: 0.05; transform: rotate(-35deg); color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\n");
      out.write("                <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\n");
      out.write("            </svg>\n");
      out.write("\n");
      out.write("            <div style=\"display: flex; align-items: center; gap: 0.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid rgba(255,255,255,0.15); margin-bottom: 1.5rem;\">\n");
      out.write("                <svg viewBox=\"0 0 100 100\" style=\"width: 45px; height: 45px;\">\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"40\" fill=\"#007bc4\" opacity=\"0.25\" stroke=\"#007bc4\" stroke-width=\"2\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"40\" ry=\"12\" fill=\"none\" stroke=\"#007bc4\" stroke-width=\"1\" opacity=\"0.5\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"12\" ry=\"40\" fill=\"none\" stroke=\"#007bc4\" stroke-width=\"1\" opacity=\"0.5\"/>\n");
      out.write("                    <!-- Jet trajectory streak -->\n");
      out.write("                    <path d=\"M15,80 Q50,45 80,25\" fill=\"none\" stroke=\"#FF9933\" stroke-width=\"3.5\" stroke-linecap=\"round\"/>\n");
      out.write("                    <!-- Jet icon -->\n");
      out.write("                    <path d=\"M80,25 L76,32 L69,27 Z\" fill=\"#FF9933\"/>\n");
      out.write("                </svg>\n");
      out.write("                <div style=\"display: flex; flex-direction: column; text-align: left; line-height: 1.1;\">\n");
      out.write("                    <span style=\"font-size: 0.9rem; font-weight: bold; color: #ffffff; letter-spacing: 1px;\">हिएलि</span>\n");
      out.write("                    <span style=\"font-size: 1.25rem; font-weight: 900; color: #007bc4; letter-spacing: 2px; font-style: italic;\">HAL</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"dashboard\">Dashboard</a></li>\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"seniority\">Seniority Engine</a></li>\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"employees?action=list\">Employee Roster</a></li>\n");
      out.write("                <li class=\"sidebar-item ");
      out.print( !isEdit ? "active" : "" );
      out.write("\"><a href=\"employees?action=new\">Add Employee</a></li>\n");
      out.write("                <li class=\"sidebar-item\" style=\"margin-top: auto;\"><a href=\"logout\" class=\"btn-logout\" style=\"color: #ff8888;\">Logout</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Content Area -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <div class=\"top-bar-title\">");
      out.print( isEdit ? "Modify Employee File" : "Register Employee File" );
      out.write("</div>\n");
      out.write("                <div class=\"user-profile\">\n");
      out.write("                    <span class=\"user-badge\">");
      out.print( currentUser.getUserRole() );
      out.write("</span>\n");
      out.write("                    <span>Welcome, <strong>");
      out.print( currentUser.getEmployeeName() );
      out.write("</strong></span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Page Container -->\n");
      out.write("            <div class=\"page-container\">\n");
      out.write("                <div class=\"actions-bar\">\n");
      out.write("                    <div>\n");
      out.write("                        <h2 style=\"color: var(--hal-navy); font-weight: 700;\">");
      out.print( isEdit ? "Edit Employee Profile" : "Add New Employee Profile" );
      out.write("</h2>\n");
      out.write("                        <p style=\"color: var(--text-light); font-size: 0.9rem;\">Fill in the master data fields. All parameters affect seniority ranking.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        <a href=\"employees?action=list\" class=\"btn btn-secondary\">&larr; Return to Roster</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");
 if (error != null) { 
      out.write("\n");
      out.write("                    <div class=\"error-message\">\n");
      out.write("                        ");
      out.print( error );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Form Card -->\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <h3 class=\"card-title\">Employee Profile Parameters</h3>\n");
      out.write("                    \n");
      out.write("                    <form action=\"employees\" method=\"post\" onsubmit=\"return validateEmployeeForm();\">\n");
      out.write("                        <input type=\"hidden\" name=\"isEditMode\" value=\"");
      out.print( isEdit );
      out.write("\">\n");
      out.write("\n");
      out.write("                        <div class=\"form-grid\">\n");
      out.write("                            <!-- Employee ID -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"employeeId\" class=\"form-label\">Employee ID (Permanent)</label>\n");
      out.write("                                <input type=\"text\" id=\"employeeId\" name=\"employeeId\" class=\"form-control\" \n");
      out.write("                                       placeholder=\"e.g. 103225\" required value=\"");
      out.print( emp.getEmployeeId() != null ? emp.getEmployeeId() : "" );
      out.write("\"\n");
      out.write("                                       ");
      out.print( isEdit ? "readonly style='background-color: #e2e8f0; cursor: not-allowed;'" : "" );
      out.write(">\n");
      out.write("                                ");
 if (isEdit) { 
      out.write("\n");
      out.write("                                    <span style=\"font-size: 0.75rem; color: var(--text-light);\">Primary identifiers are non-modifiable.</span>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Employee Name -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"employeeName\" class=\"form-label\">Full Name</label>\n");
      out.write("                                <input type=\"text\" id=\"employeeName\" name=\"employeeName\" class=\"form-control\" \n");
      out.write("                                       placeholder=\"Enter Full Name\" required value=\"");
      out.print( emp.getEmployeeName() != null ? emp.getEmployeeName() : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Department -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"department\" class=\"form-label\">Department</label>\n");
      out.write("                                <input type=\"text\" id=\"department\" name=\"department\" class=\"form-control\" \n");
      out.write("                                       placeholder=\"e.g. OVERHAUL, LCA, SERVICES\" required value=\"");
      out.print( emp.getDepartment() != null ? emp.getDepartment() : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Designation -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"designation\" class=\"form-label\">Designation</label>\n");
      out.write("                                <input type=\"text\" id=\"designation\" name=\"designation\" class=\"form-control\" \n");
      out.write("                                       placeholder=\"e.g. GM(O), AGM, HST(F)-J\" required value=\"");
      out.print( emp.getDesignation() != null ? emp.getDesignation() : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Grade selection -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"grade\" class=\"form-label\">Grade</label>\n");
      out.write("                                <select id=\"grade\" name=\"grade\" class=\"form-control\" required>\n");
      out.write("                                    ");
 for (int g = 1; g <= 10; g++) { 
                                        String currentG = "Grade " + g;
                                        boolean selected = currentG.equals(emp.getGrade());
                                    
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print( currentG );
      out.write('"');
      out.write(' ');
      out.print( selected ? "selected" : "" );
      out.write('>');
      out.print( currentG );
      out.write("</option>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Level (Hidden for backend compatibility) -->\n");
      out.write("                            <input type=\"hidden\" name=\"empLevel\" value=\"Level 1\">\n");
      out.write("\n");
      out.write("                            <!-- Date of Birth -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"dateOfBirth\" class=\"form-label\">Date of Birth</label>\n");
      out.write("                                <input type=\"date\" id=\"dateOfBirth\" name=\"dateOfBirth\" class=\"form-control\" required value=\"");
      out.print( dobDateStr );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Date of Joining -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"dateOfJoining\" class=\"form-label\">Date of Joining (DOJ)</label>\n");
      out.write("                                <input type=\"date\" id=\"dateOfJoining\" name=\"dateOfJoining\" class=\"form-control\" required value=\"");
      out.print( dojDateStr );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Promotion Date -->\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label for=\"promotionDate\" class=\"form-label\">Current Grade Promotion Date</label>\n");
      out.write("                                <input type=\"date\" id=\"promotionDate\" name=\"promotionDate\" class=\"form-control\" required value=\"");
      out.print( promoDateStr );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div style=\"display: flex; gap: 1rem; margin-top: 2rem;\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\">");
      out.print( isEdit ? "Update File" : "Save Record" );
      out.write("</button>\n");
      out.write("                            <a href=\"employees?action=list\" class=\"btn btn-secondary\">Cancel</a>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
