/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-19 17:20:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.hal.hrms.model.Employee;
import com.hal.hrms.model.User;
import com.hal.hrms.model.Promotion;

public final class employee_002dlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hal.hrms.model.Promotion");
    _jspx_imports_classes.add("com.hal.hrms.model.Employee");
    _jspx_imports_classes.add("com.hal.hrms.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    User currentUser = (User) session.getAttribute("currentUser");
    if (currentUser == null) {
        response.sendRedirect("login");
        return;
    }
    List employeeList = (List) request.getAttribute("employeeList");
    String searchQuery = (String) request.getAttribute("searchQuery");
    if (searchQuery == null) {
        searchQuery = "";
    }
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MMM-yyyy");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Employee Roster - HAL HR Seniority System</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --hal-navy: #0A2540;\n");
      out.write("            --hal-blue: #004b87;\n");
      out.write("            --hal-accent: #007bc4;\n");
      out.write("            --text-dark: #2d3748;\n");
      out.write("            --text-light: #718096;\n");
      out.write("            --bg-light: #f7fafc;\n");
      out.write("            --bg-card: #ffffff;\n");
      out.write("            --border-color: #cbd5e0;\n");
      out.write("            --danger-red: #e53e3e;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("            line-height: 1.5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .app-container {\n");
      out.write("            display: flex;\n");
      out.write("            min-height: 100vh;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Sidebar Styling */\n");
      out.write("        .sidebar {\n");
      out.write("            width: 260px;\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            color: #ffffff;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            padding: 1.5rem 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-brand {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            padding-bottom: 2rem;\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.15);\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-menu {\n");
      out.write("            list-style: none;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a {\n");
      out.write("            display: block;\n");
      out.write("            color: rgba(255,255,255,0.8);\n");
      out.write("            text-decoration: none;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-weight: 500;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .sidebar-item a:hover,\n");
      out.write("        .sidebar-item.active a {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("            padding-left: 1.25rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Main Content Container */\n");
      out.write("        .main-content {\n");
      out.write("            flex: 1;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            height: 70px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            padding: 0 2rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .top-bar-title {\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-profile {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .user-badge {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            padding: 0.25rem 0.75rem;\n");
      out.write("            border-radius: 20px;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-logout {\n");
      out.write("            color: #e53e3e;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .page-container {\n");
      out.write("            padding: 2rem;\n");
      out.write("            max-width: 1200px;\n");
      out.write("            width: 100%;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Card Component */\n");
      out.write("        .card {\n");
      out.write("            background-color: var(--bg-card);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-title {\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            margin-bottom: 1.25rem;\n");
      out.write("            border-bottom: 2px solid var(--bg-light);\n");
      out.write("            padding-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Tables */\n");
      out.write("        .table-responsive {\n");
      out.write("            overflow-x: auto;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table th {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            color: #ffffff;\n");
      out.write("            text-align: left;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border: 1px solid var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table td {\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table tbody tr:nth-child(even) {\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .data-table tbody tr:hover {\n");
      out.write("            background-color: #ebf8ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Forms inputs */\n");
      out.write("        .form-control {\n");
      out.write("            padding: 0.625rem;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            width: 100%;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: var(--hal-blue);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Buttons styling */\n");
      out.write("        .btn {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            padding: 0.625rem 1.25rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border: 1px solid transparent;\n");
      out.write("            transition: background-color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            border-color: var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-secondary:hover {\n");
      out.write("            background-color: #cbd5e0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .actions-bar {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("            gap: 1rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @media print {\n");
      out.write("            .sidebar, .top-bar, .actions-bar, .btn, .no-print, form {\n");
      out.write("                display: none !important;\n");
      out.write("            }\n");
      out.write("            .main-content {\n");
      out.write("                padding: 0 !important;\n");
      out.write("            }\n");
      out.write("            .page-container {\n");
      out.write("                padding: 0 !important;\n");
      out.write("                max-width: 100% !important;\n");
      out.write("            }\n");
      out.write("            .card {\n");
      out.write("                border: none !important;\n");
      out.write("                box-shadow: none !important;\n");
      out.write("                padding: 0 !important;\n");
      out.write("            }\n");
      out.write("            .data-table th {\n");
      out.write("                background-color: #f2f2f2 !important;\n");
      out.write("                color: #000000 !important;\n");
      out.write("                border: 1px solid #000000 !important;\n");
      out.write("            }\n");
      out.write("            .data-table td {\n");
      out.write("                border: 1px solid #000000 !important;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modal Backdrop */\n");
      out.write("        .modal-overlay {\n");
      out.write("            display: none;\n");
      out.write("            position: fixed;\n");
      out.write("            z-index: 1000;\n");
      out.write("            left: 0;\n");
      out.write("            top: 0;\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            overflow: auto;\n");
      out.write("            background-color: rgba(10, 37, 64, 0.4);\n");
      out.write("            backdrop-filter: blur(8px);\n");
      out.write("            -webkit-backdrop-filter: blur(8px);\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modal Container */\n");
      out.write("        .modal-container {\n");
      out.write("            background-color: #ffffff;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            width: 90%;\n");
      out.write("            max-width: 650px;\n");
      out.write("            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            animation: modalSlideUp 0.3s ease-out;\n");
      out.write("            max-height: 85vh;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes modalSlideUp {\n");
      out.write("            from {\n");
      out.write("                transform: translateY(30px);\n");
      out.write("                opacity: 0;\n");
      out.write("            }\n");
      out.write("            to {\n");
      out.write("                transform: translateY(0);\n");
      out.write("                opacity: 1;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modal Header */\n");
      out.write("        .modal-header {\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            border-bottom: 1px solid var(--border-color);\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("            border-top-left-radius: 12px;\n");
      out.write("            border-top-right-radius: 12px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header-title {\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            font-size: 1.25rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal-header-subtitle {\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--text-light);\n");
      out.write("            margin-top: 0.25rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-modal-close {\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            color: var(--text-light);\n");
      out.write("            font-size: 1.75rem;\n");
      out.write("            cursor: pointer;\n");
      out.write("            line-height: 1;\n");
      out.write("            padding: 0.25rem;\n");
      out.write("            transition: color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-modal-close:hover {\n");
      out.write("            color: var(--danger-red);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Modal Body */\n");
      out.write("        .modal-body {\n");
      out.write("            padding: 1.5rem;\n");
      out.write("            overflow-y: auto;\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Timeline Tree/List */\n");
      out.write("        .timeline-wrapper {\n");
      out.write("            position: relative;\n");
      out.write("            padding-left: 2rem;\n");
      out.write("            margin: 1rem 0;\n");
      out.write("            border-left: 2px solid var(--border-color);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-item {\n");
      out.write("            position: relative;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-item:last-child {\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-badge {\n");
      out.write("            position: absolute;\n");
      out.write("            left: calc(-2rem - 7px);\n");
      out.write("            top: 6px;\n");
      out.write("            width: 12px;\n");
      out.write("            height: 12px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            background-color: var(--border-color);\n");
      out.write("            border: 2px solid #ffffff;\n");
      out.write("            box-shadow: 0 0 0 2px var(--border-color);\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-item.primary-assignment .timeline-badge {\n");
      out.write("            background-color: var(--hal-accent);\n");
      out.write("            box-shadow: 0 0 0 2px var(--hal-accent);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-card {\n");
      out.write("            background-color: var(--bg-light);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            padding: 1rem;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-item.primary-assignment .timeline-card {\n");
      out.write("            border-left: 4px solid var(--hal-accent);\n");
      out.write("            background-color: #f0f7ff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: flex-start;\n");
      out.write("            margin-bottom: 0.75rem;\n");
      out.write("            gap: 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-designation {\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            font-size: 1.05rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Assignment Type Tags */\n");
      out.write("        .assignment-type-tag {\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            padding: 0.2rem 0.6rem;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            white-space: nowrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-trainee {\n");
      out.write("            background-color: #edf2f7;\n");
      out.write("            color: #4a5568;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-absorption {\n");
      out.write("            background-color: #ebf8ff;\n");
      out.write("            color: #2b6cb0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-cps {\n");
      out.write("            background-color: #e6fffa;\n");
      out.write("            color: #234e52;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-dpc {\n");
      out.write("            background-color: #faf5ff;\n");
      out.write("            color: #553c9a;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-transfer {\n");
      out.write("            background-color: #fffaf0;\n");
      out.write("            color: #dd6b20;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-job-rotation {\n");
      out.write("            background-color: #f0fff4;\n");
      out.write("            color: #22543d;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-revised-designation {\n");
      out.write("            background-color: #e2e8f0;\n");
      out.write("            color: #4a5568;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .type-additional-responsibilities {\n");
      out.write("            background-color: #fff5f5;\n");
      out.write("            color: #9b2c2c;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline-details {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .detail-item strong {\n");
      out.write("            color: var(--text-light);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .no-history {\n");
      out.write("            text-align: center;\n");
      out.write("            color: var(--text-light);\n");
      out.write("            padding: 2rem;\n");
      out.write("            font-style: italic;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        /**\n");
      out.write("         * Exports HTML Table data directly into a CSV Spreadsheet.\n");
      out.write("         * Works natively in client web browser without server load.\n");
      out.write("         */\n");
      out.write("        function exportTableToCSV(tableId, filename) {\n");
      out.write("            var csv = [];\n");
      out.write("            var table = document.getElementById(tableId);\n");
      out.write("            if (!table) return;\n");
      out.write("\n");
      out.write("            var rows = table.querySelectorAll(\"tr\");\n");
      out.write("            \n");
      out.write("            for (var i = 0; i < rows.length; i++) {\n");
      out.write("                var row = [];\n");
      out.write("                var cols = rows[i].querySelectorAll(\"td, th\");\n");
      out.write("                \n");
      out.write("                // Skip the Actions column header and cell data if this is admin view\n");
      out.write("                var limit = cols.length;\n");
      out.write("                var isAdmin = \"");
      out.print( currentUser.getUserRole() );
      out.write("\" === \"ADMIN\";\n");
      out.write("                if (isAdmin && i > 0) {\n");
      out.write("                    limit = cols.length - 1; // skip last td (actions)\n");
      out.write("                } else if (isAdmin && i == 0) {\n");
      out.write("                    limit = cols.length - 1; // skip last th (actions)\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                for (var j = 0; j < limit; j++) {\n");
      out.write("                    var cellText = cols[j].innerText.trim();\n");
      out.write("                    cellText = cellText.replace(/\"/g, '\"\"'); // Escape double quotes\n");
      out.write("                    row.push('\"' + cellText + '\"');\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                csv.push(row.join(\",\"));\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            var csvFile = new Blob([csv.join(\"\\n\")], { type: \"text/csv;charset=utf-8;\" });\n");
      out.write("            var downloadLink = document.createElement(\"a\");\n");
      out.write("            \n");
      out.write("            downloadLink.download = filename;\n");
      out.write("            downloadLink.href = window.URL.createObjectURL(csvFile);\n");
      out.write("            downloadLink.style.display = \"none\";\n");
      out.write("            document.body.appendChild(downloadLink);\n");
      out.write("            downloadLink.click();\n");
      out.write("            document.body.removeChild(downloadLink);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"app-container\" style=\"position: relative; padding-top: 4px;\">\n");
      out.write("        <!-- Tricolor Top Accent -->\n");
      out.write("        <div style=\"height: 4px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%); z-index: 100;\"></div>\n");
      out.write("\n");
      out.write("        <!-- Sidebar Navigation -->\n");
      out.write("        <div class=\"sidebar\" style=\"position: relative; overflow: hidden; padding-top: 2rem;\">\n");
      out.write("            <!-- Jet watermark inside sidebar -->\n");
      out.write("            <svg style=\"position: absolute; bottom: -20px; right: -20px; width: 120px; height: 120px; opacity: 0.05; transform: rotate(-35deg); color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\n");
      out.write("                <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\n");
      out.write("            </svg>\n");
      out.write("\n");
      out.write("            <div style=\"display: flex; align-items: center; gap: 0.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid rgba(255,255,255,0.15); margin-bottom: 1.5rem;\">\n");
      out.write("                <svg viewBox=\"0 0 100 100\" style=\"width: 45px; height: 45px;\">\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"40\" fill=\"#007bc4\" opacity=\"0.25\" stroke=\"#007bc4\" stroke-width=\"2\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"40\" ry=\"12\" fill=\"none\" stroke=\"#007bc4\" stroke-width=\"1\" opacity=\"0.5\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"12\" ry=\"40\" fill=\"none\" stroke=\"#007bc4\" stroke-width=\"1\" opacity=\"0.5\"/>\n");
      out.write("                    <!-- Jet trajectory streak -->\n");
      out.write("                    <path d=\"M15,80 Q50,45 80,25\" fill=\"none\" stroke=\"#FF9933\" stroke-width=\"3.5\" stroke-linecap=\"round\"/>\n");
      out.write("                    <!-- Jet icon -->\n");
      out.write("                    <path d=\"M80,25 L76,32 L69,27 Z\" fill=\"#FF9933\"/>\n");
      out.write("                </svg>\n");
      out.write("                <div style=\"display: flex; flex-direction: column; text-align: left; line-height: 1.1;\">\n");
      out.write("                    <span style=\"font-size: 0.9rem; font-weight: bold; color: #ffffff; letter-spacing: 1px;\">हिएलि</span>\n");
      out.write("                    <span style=\"font-size: 1.25rem; font-weight: 900; color: #007bc4; letter-spacing: 2px; font-style: italic;\">HAL</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"sidebar-menu\">\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"dashboard\">Dashboard</a></li>\n");
      out.write("                <li class=\"sidebar-item\"><a href=\"seniority\">Seniority Engine</a></li>\n");
      out.write("                <li class=\"sidebar-item active\"><a href=\"employees?action=list\">Employee Roster</a></li>\n");
      out.write("                ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\n");
      out.write("                    <li class=\"sidebar-item\"><a href=\"employees?action=new\">Add Employee</a></li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <li class=\"sidebar-item\" style=\"margin-top: auto;\"><a href=\"logout\" class=\"btn-logout\" style=\"color: #ff8888;\">Logout</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Main Content Area -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <div class=\"top-bar-title\">Employee Records Directory</div>\n");
      out.write("                <div class=\"user-profile\">\n");
      out.write("                    <span class=\"user-badge\">");
      out.print( currentUser.getUserRole() );
      out.write("</span>\n");
      out.write("                    <span>Welcome, <strong>");
      out.print( currentUser.getEmployeeName() );
      out.write("</strong></span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Page Content -->\n");
      out.write("            <div class=\"page-container\">\n");
      out.write("                <div class=\"actions-bar\">\n");
      out.write("                    <div>\n");
      out.write("                        <h2 style=\"color: var(--hal-navy); font-weight: 700;\">Active Employees Roster</h2>\n");
      out.write("                        <p style=\"color: var(--text-light); font-size: 0.9rem;\">Maintain active profiles and trace administrative parameters.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div>\n");
      out.write("                        ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\n");
      out.write("                            <a href=\"employees?action=new\" class=\"btn btn-primary\">+ Add New Employee</a>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Search Card -->\n");
      out.write("                <div class=\"card\" style=\"padding: 1rem;\">\n");
      out.write("                    <form action=\"employees\" method=\"get\" style=\"display: flex; gap: 1rem; align-items: center;\">\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"list\">\n");
      out.write("                        <input type=\"text\" name=\"query\" class=\"form-control\" placeholder=\"Search by ID, Name, Department, or Designation...\" value=\"");
      out.print( searchQuery );
      out.write("\" style=\"flex: 1;\">\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Search</button>\n");
      out.write("                        ");
 if (!"".equals(searchQuery)) { 
      out.write("\n");
      out.write("                            <a href=\"employees?action=list\" class=\"btn btn-secondary\">Clear</a>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Roster Grid -->\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;\">\n");
      out.write("                        <h3 class=\"card-title\" style=\"margin-bottom: 0; border: none;\">Employee Directory Listings</h3>\n");
      out.write("                        <button onclick=\"exportTableToCSV('rosterTable', 'hal_employee_roster.csv')\" class=\"btn btn-secondary\">Export to CSV</button>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"table-responsive\">\n");
      out.write("                        ");

                            boolean[] activeGrades = new boolean[11]; // index 1 to 10
                            int activeGradesCount = 0;
                            if (employeeList != null && !employeeList.isEmpty()) {
                                for (int i = 0; i < employeeList.size(); i++) {
                                    Employee emp = (Employee) employeeList.get(i);
                                    for (int g = 1; g <= 10; g++) {
                                        if (emp.getPromotionDateForGrade("Grade " + g) != null) {
                                            if (!activeGrades[g]) {
                                                activeGrades[g] = true;
                                                activeGradesCount++;
                                            }
                                        }
                                    }
                                }
                            }
                            if (activeGradesCount == 0) {
                                if (employeeList != null && !employeeList.isEmpty()) {
                                    Employee emp = (Employee) employeeList.get(0);
                                    String gName = emp.getGrade();
                                    if (gName != null && gName.startsWith("Grade ")) {
                                        try {
                                            int g = Integer.parseInt(gName.substring(6).trim());
                                            activeGrades[g] = true;
                                            activeGradesCount = 1;
                                        } catch (Exception e) {}
                                    }
                                }
                            }
                            int totalColsCount = ("ADMIN".equals(currentUser.getUserRole()) ? 9 : 8) + activeGradesCount;
                        
      out.write("\n");
      out.write("                        <table class=\"data-table\" id=\"rosterTable\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Employee ID</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Full Name</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Grade</th>\n");
      out.write("                                    ");
 if (activeGradesCount > 0) { 
      out.write("\n");
      out.write("                                        <th colspan=\"");
      out.print( activeGradesCount );
      out.write("\" style=\"text-align: center; border-bottom: 1px solid rgba(255,255,255,0.2);\">Promotion Dates per Grade (Position)</th>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Joining</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Date of Birth</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Retirement Date</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Department</th>\n");
      out.write("                                    <th rowspan=\"2\" style=\"vertical-align: middle;\">Designation</th>\n");
      out.write("                                    ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\n");
      out.write("                                        <th rowspan=\"2\" class=\"no-print\" style=\"width: 130px; text-align: center; vertical-align: middle;\">Actions</th>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    ");
 for (int g = 1; g <= 10; g++) { 
                                        if (activeGrades[g]) {
                                            String dName = Employee.getDesignationForGrade("Grade " + g);
                                            String shortD = dName.indexOf("(") > -1 ? dName.substring(dName.indexOf("(")+1, dName.indexOf(")")) : dName;
                                    
      out.write("\n");
      out.write("                                        <th style=\"font-size: 0.8rem; padding: 0.5rem; text-align: center; min-width: 90px;\">\n");
      out.write("                                            Gr ");
      out.print( g );
      out.write("<br><span style=\"font-size:0.7rem; font-weight:normal; opacity:0.85;\">");
      out.print( shortD );
      out.write("</span>\n");
      out.write("                                        </th>\n");
      out.write("                                    ");
 
                                        }
                                    } 
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");

                                    if (employeeList != null && !employeeList.isEmpty()) {
                                        for (int i = 0; i < employeeList.size(); i++) {
                                            Employee emp = (Employee) employeeList.get(i);
                                
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td><strong>");
      out.print( emp.getEmployeeId() );
      out.write("</strong></td>\n");
      out.write("                                        <td>\n");
      out.write("                                            <a href=\"javascript:void(0)\" onclick=\"showTimelineModal('");
      out.print( emp.getEmployeeId() );
      out.write("')\" style=\"color: var(--hal-blue); text-decoration: underline; font-weight: 600;\">");
      out.print( emp.getEmployeeName() );
      out.write("</a>\n");
      out.write("                                            <div id=\"history-data-");
      out.print( emp.getEmployeeId() );
      out.write("\" style=\"display: none;\">\n");
      out.write("                                                [\n");
      out.write("                                                ");

                                                    List history = emp.getHistoryList();
                                                    if (history != null) {
                                                        for (int j = 0; j < history.size(); j++) {
                                                            Promotion promo = (Promotion) history.get(j);
                                                            String validFromStr = promo.getValidFrom() != null ? sdf.format(promo.getValidFrom()) : "N/A";
                                                            String validToStr = promo.getValidTo() != null ? sdf.format(promo.getValidTo()) : "Present";
                                                            String promoDateStr = promo.getPromotionDate() != null ? sdf.format(promo.getPromotionDate()) : "N/A";
                                                            String des = promo.getDesignation() != null ? promo.getDesignation() : "";
                                                            des = des.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String gr = promo.getGrade() != null ? promo.getGrade() : "";
                                                            gr = gr.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String type = promo.getAssignmentType() != null ? promo.getAssignmentType() : "";
                                                            type = type.replace("\\", "\\\\").replace("\"", "\\\"");
                                                            String ord = promo.getOrderNumber() != null ? promo.getOrderNumber() : "N/A";
                                                            ord = ord.replace("\\", "\\\\").replace("\"", "\\\"");
                                                
      out.write("\n");
      out.write("                                                    {\n");
      out.write("                                                        \"grade\": \"");
      out.print( gr );
      out.write("\",\n");
      out.write("                                                        \"promotionDate\": \"");
      out.print( promoDateStr );
      out.write("\",\n");
      out.write("                                                        \"designation\": \"");
      out.print( des );
      out.write("\",\n");
      out.write("                                                        \"validFrom\": \"");
      out.print( validFromStr );
      out.write("\",\n");
      out.write("                                                        \"validTo\": \"");
      out.print( validToStr );
      out.write("\",\n");
      out.write("                                                        \"isPrimary\": ");
      out.print( promo.getIsPrimary() );
      out.write(",\n");
      out.write("                                                        \"assignmentType\": \"");
      out.print( type );
      out.write("\",\n");
      out.write("                                                        \"orderNumber\": \"");
      out.print( ord );
      out.write("\"\n");
      out.write("                                                    }");
      out.print( (j < history.size() - 1) ? "," : "" );
      out.write("\n");
      out.write("                                                ");

                                                        }
                                                    }
                                                
      out.write("\n");
      out.write("                                                ]\n");
      out.write("                                            </div>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td>");
      out.print( emp.getGrade() );
      out.write("</td>\n");
      out.write("                                        \n");
      out.write("                                        ");
 for (int g = 1; g <= 10; g++) { 
                                            if (activeGrades[g]) {
                                                java.util.Date pDate = emp.getPromotionDateForGrade("Grade " + g);
                                        
      out.write("\n");
      out.write("                                            <td style=\"text-align: center; font-size: 0.85rem;\">\n");
      out.write("                                                ");
      out.print( pDate != null ? sdf.format(pDate) : "-" );
      out.write("\n");
      out.write("                                            </td>\n");
      out.write("                                        ");
 
                                            }
                                        } 
      out.write("\n");
      out.write("                                        \n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfJoining()) );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( sdf.format(emp.getDateOfBirth()) );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDateOfRetirement() != null ? sdf.format(emp.getDateOfRetirement()) : "N/A" );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDepartment() );
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( emp.getDesignation() );
      out.write("</td>\n");
      out.write("                                        ");
 if ("ADMIN".equals(currentUser.getUserRole())) { 
      out.write("\n");
      out.write("                                            <td class=\"no-print\" style=\"text-align: center;\">\n");
      out.write("                                                <a href=\"employees?action=edit&id=");
      out.print( emp.getEmployeeId() );
      out.write("\" style=\"color: var(--hal-blue); text-decoration: none; font-weight: bold; margin-right: 0.75rem;\">Edit</a>\n");
      out.write("                                                <a href=\"employees?action=delete&id=");
      out.print( emp.getEmployeeId() );
      out.write("\" onclick=\"return confirm('Are you sure you want to delete this employee?');\" style=\"color: var(--danger-red); text-decoration: none; font-weight: bold;\">Delete</a>\n");
      out.write("                                            </td>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </tr>\n");
      out.write("                                ");

                                        }
                                    } else {
                                
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td colspan=\"");
      out.print( totalColsCount );
      out.write("\" style=\"text-align: center; color: var(--text-light); padding: 2rem;\">\n");
      out.write("                                            No employee records found.\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");

                                    }
                                
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Timeline Modal -->\n");
      out.write("    <div id=\"timelineModal\" class=\"modal-overlay\">\n");
      out.write("        <div class=\"modal-container\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <div>\n");
      out.write("                    <h3 class=\"modal-header-title\" id=\"modalEmployeeName\">Employee Name</h3>\n");
      out.write("                    <div class=\"modal-header-subtitle\">Employee ID: <span id=\"modalEmployeeId\">N/A</span></div>\n");
      out.write("                </div>\n");
      out.write("                <button class=\"btn-modal-close\" onclick=\"closeTimelineModal()\">&times;</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <div class=\"timeline-wrapper\" id=\"timelineContent\">\n");
      out.write("                    <!-- Dynamic Timeline Content will be inserted here -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function showTimelineModal(empId) {\n");
      out.write("            var dataElement = document.getElementById(\"history-data-\" + empId);\n");
      out.write("            var history = [];\n");
      out.write("            if (dataElement) {\n");
      out.write("                try {\n");
      out.write("                    history = JSON.parse(dataElement.textContent || dataElement.innerText);\n");
      out.write("                } catch(e) {\n");
      out.write("                    console.error(\"Error parsing history JSON for employee \" + empId, e);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            var empName = \"\";\n");
      out.write("            \n");
      out.write("            // Find employee name\n");
      out.write("            var rows = document.querySelectorAll(\"#rosterTable tbody tr\");\n");
      out.write("            for (var i = 0; i < rows.length; i++) {\n");
      out.write("                var cellId = rows[i].cells[0].innerText.trim();\n");
      out.write("                if (cellId === empId) {\n");
      out.write("                    // Link is inside the second cell\n");
      out.write("                    empName = rows[i].cells[1].innerText.trim();\n");
      out.write("                    break;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById(\"modalEmployeeId\").innerText = empId;\n");
      out.write("            document.getElementById(\"modalEmployeeName\").innerText = empName;\n");
      out.write("            \n");
      out.write("            var timelineContainer = document.getElementById(\"timelineContent\");\n");
      out.write("            timelineContainer.innerHTML = \"\";\n");
      out.write("            \n");
      out.write("            if (!history || history.length === 0) {\n");
      out.write("                timelineContainer.innerHTML = \"<div class='no-history'>No promotion or assignment history recorded for this employee.</div>\";\n");
      out.write("            } else {\n");
      out.write("                // Sort history by validFrom to make sure it's chronological\n");
      out.write("                var months = { \"Jan\":0, \"Feb\":1, \"Mar\":2, \"Apr\":3, \"May\":4, \"Jun\":5, \"Jul\":6, \"Aug\":7, \"Sep\":8, \"Oct\":9, \"Nov\":10, \"Dec\":11 };\n");
      out.write("                function parseCustomDate(dateStr) {\n");
      out.write("                    if (!dateStr || dateStr === \"N/A\" || dateStr === \"Present\") return new Date();\n");
      out.write("                    var parts = dateStr.split(\"-\");\n");
      out.write("                    if (parts.length < 3) return new Date();\n");
      out.write("                    var day = parseInt(parts[0], 10);\n");
      out.write("                    var month = months[parts[1]];\n");
      out.write("                    var year = parseInt(parts[2], 10);\n");
      out.write("                    return new Date(year, month, day);\n");
      out.write("                }\n");
      out.write("                \n");
      out.write("                // Clone and sort\n");
      out.write("                var sortedHistory = [];\n");
      out.write("                for (var k = 0; k < history.length; k++) {\n");
      out.write("                    sortedHistory.push(history[k]);\n");
      out.write("                }\n");
      out.write("                sortedHistory.sort(function(a, b) {\n");
      out.write("                    return parseCustomDate(a.validFrom) - parseCustomDate(b.validFrom);\n");
      out.write("                });\n");
      out.write("                \n");
      out.write("                var html = \"\";\n");
      out.write("                for (var i = 0; i < sortedHistory.length; i++) {\n");
      out.write("                    var item = sortedHistory[i];\n");
      out.write("                    var badgeClass = item.isPrimary ? \"badge-primary\" : \"badge-secondary\";\n");
      out.write("                    var typeClass = \"type-\" + item.assignmentType.toLowerCase().replace(/[^a-z0-9]/g, \"-\");\n");
      out.write("                    \n");
      out.write("                    html += \"<div class='timeline-item \" + (item.isPrimary ? \"primary-assignment\" : \"\") + \"'>\";\n");
      out.write("                    html += \"  <div class='timeline-badge \" + badgeClass + \"'></div>\";\n");
      out.write("                    html += \"  <div class='timeline-card'>\";\n");
      out.write("                    html += \"    <div class='timeline-header'>\";\n");
      out.write("                    html += \"      <span class='timeline-designation'>Pos Code: \" + item.designation + \"</span>\";\n");
      out.write("                    html += \"      <span class='assignment-type-tag \" + typeClass + \"'>\" + item.assignmentType + \"</span>\";\n");
      out.write("                    html += \"    </div>\";\n");
      out.write("                    html += \"    <div class='timeline-details'>\";\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Grade:</strong> \" + item.grade + \"</div>\";\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Promotion Date:</strong> \" + item.promotionDate + \"</div>\";\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Duration:</strong> \" + item.validFrom + \" to \" + item.validTo + \"</div>\";\n");
      out.write("                    html += \"      <div class='detail-item'><strong>Order Number:</strong> \" + item.orderNumber + \"</div>\";\n");
      out.write("                    html += \"    </div>\";\n");
      out.write("                    html += \"  </div>\";\n");
      out.write("                    html += \"</div>\";\n");
      out.write("                }\n");
      out.write("                timelineContainer.innerHTML = html;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            document.getElementById(\"timelineModal\").style.display = \"flex\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function closeTimelineModal() {\n");
      out.write("            document.getElementById(\"timelineModal\").style.display = \"none\";\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Close modal on click outside content\n");
      out.write("        window.onclick = function(event) {\n");
      out.write("            var modal = document.getElementById(\"timelineModal\");\n");
      out.write("            if (event.target == modal) {\n");
      out.write("                modal.style.display = \"none\";\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
