/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2026-06-18 15:05:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Login - HAL HR Seniority Management System</title>\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --hal-navy: #0A2540;\n");
      out.write("            --hal-blue: #004b87;\n");
      out.write("            --text-dark: #2d3748;\n");
      out.write("            --text-light: #718096;\n");
      out.write("            --bg-light: #f7fafc;\n");
      out.write("            --border-color: #cbd5e0;\n");
      out.write("            --danger-red: #e53e3e;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            line-height: 1.5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-card {\n");
      out.write("            background: #ffffff;\n");
      out.write("            padding: 2.5rem;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 440px;\n");
      out.write("            box-shadow: 0 10px 25px rgba(0,0,0,0.25);\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-header {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-logo {\n");
      out.write("            font-size: 1.75rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            color: var(--hal-navy);\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-subtitle {\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            color: var(--text-light);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            gap: 0.375rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-label {\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--text-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            padding: 0.625rem;\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            width: 100%;\n");
      out.write("            outline: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            border-color: var(--hal-blue);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn {\n");
      out.write("            display: block;\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.75rem;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            font-weight: bold;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("            background-color: var(--hal-blue);\n");
      out.write("            color: #ffffff;\n");
      out.write("            transition: background-color 0.2s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn:hover {\n");
      out.write("            background-color: var(--hal-navy);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .error-message {\n");
      out.write("            background-color: #fff5f5;\n");
      out.write("            border-left: 4px solid var(--danger-red);\n");
      out.write("            color: var(--danger-red);\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            margin-bottom: 1.25rem;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Jet watermark background -->\n");
      out.write("    <svg style=\"position: fixed; bottom: -5%; right: -5%; width: 45%; height: 45%; opacity: 0.04; transform: rotate(-35deg); color: #ffffff; pointer-events: none;\" viewBox=\"0 0 100 100\" fill=\"currentColor\">\n");
      out.write("        <path d=\"M50 5 L53 25 L85 55 L85 62 L54 50 L53 85 L65 92 L65 95 L50 90 L35 95 L35 92 L47 85 L46 50 L15 62 L15 55 L47 25 Z\" />\n");
      out.write("    </svg>\n");
      out.write("\n");
      out.write("    <div class=\"login-card\">\n");
      out.write("        <!-- Tricolor Top Accent -->\n");
      out.write("        <div style=\"height: 5px; width: 100%; position: absolute; top: 0; left: 0; background: linear-gradient(to right, #FF9933 33.33%, #FFFFFF 33.33%, #FFFFFF 66.66%, #138808 66.66%);\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"login-header\">\n");
      out.write("            <div style=\"display: flex; justify-content: center; align-items: center; gap: 0.5rem; margin-bottom: 1.25rem;\">\n");
      out.write("                <svg viewBox=\"0 0 100 100\" style=\"width: 55px; height: 55px;\">\n");
      out.write("                    <circle cx=\"50\" cy=\"50\" r=\"40\" fill=\"#004b87\" opacity=\"0.15\" stroke=\"#004b87\" stroke-width=\"2\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"40\" ry=\"12\" fill=\"none\" stroke=\"#004b87\" stroke-width=\"1\" opacity=\"0.4\"/>\n");
      out.write("                    <ellipse cx=\"50\" cy=\"50\" rx=\"12\" ry=\"40\" fill=\"none\" stroke=\"#004b87\" stroke-width=\"1\" opacity=\"0.4\"/>\n");
      out.write("                    <!-- Jet trajectory streak -->\n");
      out.write("                    <path d=\"M15,80 Q50,45 80,25\" fill=\"none\" stroke=\"#FF9933\" stroke-width=\"3.5\" stroke-linecap=\"round\"/>\n");
      out.write("                    <!-- Jet icon -->\n");
      out.write("                    <path d=\"M80,25 L76,32 L69,27 Z\" fill=\"#FF9933\"/>\n");
      out.write("                </svg>\n");
      out.write("                <div style=\"display: flex; flex-direction: column; text-align: left; line-height: 1.1;\">\n");
      out.write("                    <span style=\"font-size: 1.1rem; font-weight: bold; color: var(--hal-navy); letter-spacing: 1px;\">हिएलि</span>\n");
      out.write("                    <span style=\"font-size: 1.5rem; font-weight: 900; color: var(--hal-blue); letter-spacing: 2px; font-style: italic;\">HAL</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <h2 style=\"font-size: 1.25rem; font-weight: 800; color: var(--hal-navy); margin-bottom: 0.25rem; text-transform: uppercase; letter-spacing: 0.5px;\">Hindustan Aeronautics Limited</h2>\n");
      out.write("            <div style=\"height: 2px; width: 60px; background-color: #FF9933; margin: 0.5rem auto;\"></div>\n");
      out.write("            <h3 style=\"font-size: 0.85rem; font-weight: 700; color: var(--text-light); text-transform: uppercase; letter-spacing: 1px;\">Employee Seniority Management System</h3>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");

            String error = (String) request.getAttribute("error");
            if (error != null) {
        
      out.write("\n");
      out.write("            <div class=\"error-message\">\n");
      out.write("                ");
      out.print( error );
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"login\" method=\"post\">\n");
      out.write("            <div class=\"form-group\" style=\"margin-bottom: 1.25rem;\">\n");
      out.write("                <label for=\"username\" class=\"form-label\">Employee ID / Username</label>\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" placeholder=\"Enter Username\" required autocomplete=\"off\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group\" style=\"margin-bottom: 1.5rem;\">\n");
      out.write("                <label for=\"password\" class=\"form-label\">Password</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Enter Password\" required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn\">Login Securely</button>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("        <div style=\"margin-top: 1.5rem; text-align: center; font-size: 0.8rem; color: var(--text-light);\">\n");
      out.write("            Hindustan Aeronautics Limited &copy; ");
      out.print( new java.text.SimpleDateFormat("yyyy").format(new java.util.Date()) );
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
